const teamData = {
  geschaeftsfuehrung: [
    {
      name: "Ulrike Niesen",
      title: "Geschäftsführung",
      phone: "05551 / 96 88-0",
      fax: "05551 / 96 88-77",
      email: "ulrike.niesen@zad-northeim.de",
      image: "niesen_ulrike",
      imageHover: "niesen_ulrike",
    },
    {
      name: "Irina Niesen",
      title: "Geschäftsführung",
      phone: "05551 / 96 88-0",
      fax: "05551 / 96 88-77",
      email: "irina.niesen@zad-northeim.de",
      image: "niesen_irina_1",
      imageHover: "niesen_irina_2",
    },
  ],
  vertrieb: [
    {
      name: "Jörg Eichenberger",
      title: "Prokurist",
      phone: "05551 / 96 88-15",
      fax: "05551 / 96 88-655",
      email: "joerg.eichenberger@zad-northeim.de",
      image: "eichenberger_1",
      imageHover: "eichenberger_2",
    },
    {
      name: "Lars Töpperwien",
      title: "Außendienst",
      phone: "05551 / 96 88-649",
      fax: "05551 / 96 88-655",
      email: "lars.toepperwien@zad-northeim.de",
      image: "toepperwien_1",
      imageHover: "toepperwien_2",
    },
    {
      name: "Norbert Schiller",
      title: "Außendienst",
      phone: "05551 / 96 88-0",
      fax: "05551 / 96 88-655",
      email: "norbert.schiller@zad-northeim.de",
      image: "schiller_1",
      imageHover: "schiller_2",
    },
    {
      name: "Markus Käppler",
      title: "Außendienst",
      phone: "05551 / 96 88-0",
      fax: "05551 / 96 88-655",
      email: "markus.kaeppler@zad-northeim.de",
      image: "kaeppler_1",
      imageHover: "kaeppler_2",
    },

    {
      name: "Simone Zahel",
      title: "Innendienst",
      phone: "05551 / 96 88-646",
      fax: "05551 / 96 88-655",
      email: "simone.zahel@zad-northeim.de",
      image: "zahel_1",
      imageHover: "zahel_2",
    },
    {
      name: "Jennifer Zinnecker",
      title: "Innendienst",
      phone: "05551 / 96 88-769",
      fax: "05551 / 96 88-655",
      email: "jennifer.zinnecker@zad-northeim.de",
      image: "zinnecker_1",
      imageHover: "zinnecker_2",
    },
  ],
  teamleitung: [
    {
      name: "Vjaceslav Ognev",
      title: "Pflegeabrechnung / Teamleitung 9",
      phone: "05551 / 96 88-209",
      fax: "05551 / 96 88-655",
      email: "vjaceslav.ognev@zad-northeim.de",
      image: "ognev_vjaceslav_1",
      imageHover: "ognev_vjaceslav_2",
    },
    {
      name: "Elke Müller",
      title: "Pflegeabrechnung / Teamleitung 10",
      phone: "05551 / 96 88-52",
      fax: "05551 / 96 88-55",
      email: "elke.mueller@zad-northeim.de",
      image: "mueller_1",
      imageHover: "mueller_2",
    },
    {
      name: "Claudia Schwarz",
      title: "Pflegeabrechnung / Teamleitung 11",
      phone: "05551 / 96 88-42",
      fax: "05551 / 96 88-688",
      email: "claudia.schwarz@zad-northeim.de",
      image: "schwarz_1",
      imageHover: "schwarz_2",
    },
    {
      name: "Birgit Elsner",
      title: "Pflegeabrechnung / Teamleitung 12",
      phone: "05551 / 96 88-21",
      fax: "05551 / 96 88-656",
      email: "birgit.elsner@zad-northeim.de",
      image: "elsner",
      imageHover: "elsner",
    },
    {
      name: "Stefanie Dobrick",
      title: "Krankentransport & Rettungsdienst / Teamleitung 21",
      phone: "05551 / 96 88-17",
      fax: "05551 / 96 88-84",
      email: "stefanie.dobrick@zad-northeim.de",
      image: "dobrick_1",
      imageHover: "dobrick_2",
    },
    {
      name: "Beate Knauer",
      title: "Krankentransport & Rettungsdienst / Teamleitung 22",
      phone: "05551 / 96 88-23",
      fax: "05551 / 96 88-88",
      email: "beate.knauer@zad-northeim.de",
      image: "knauer",
      imageHover: "knauer",
    },
    {
      name: "Maria Lasota",
      title: "Stellv. Teamleitung 22",
      phone: "05551 / 96 88-0",
      fax: "05551 / 96 88-88",
      email: "maria.lasota@zad-northeim.de",
      image: "lasota_1",
      imageHover: "lasota_2",
    },
    {
      name: "Alexander Niesen",
      title: "IT / Teamleitung",
      phone: "05551 / 96 88-0",
      fax: "05551 / 96 88-655",
      email: "alexander.niesen@zad-northeim.de",
      image: "aniesen_1",
      imageHover: "aniesen_2",
    },
  ],
  zentrale: [
    {
      name: "Kathrin Schuster",
      title: "Zentrale",
      phone: "05551 / 96 88-0",
      fax: "05551 / 96 88-88",
      image: "schuster_1",
      imageHover: "schuster_2",
    },
    {
      name: "Heike Manteufel",
      title: "Zentrale",
      phone: "05551 / 96 88-0",
      fax: "05551 / 96 88-88",
      image: "manteufel_1",
      imageHover: "manteufel_2",
    },
  ],
};

export default teamData;
